# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- none

pr:
- none

pool:
  vmImage: 'ubuntu-latest'

- task: SqlAzureDacpacDeployment@1
  inputs:
    azureSubscription: 'knol-subs_vsenterprise-rg_poc-svcconn'
    AuthenticationType: 'aadAuthenticationIntegrated'
    ServerName: 'angulartest.database.windows.net'
    DatabaseName: 'angulartestdb'
    deployType: 'InlineSqlTask'
    SqlInline: 'select getdate()'
    IpDetectionMethod: 'AutoDetect'
